// bank-list.js
// Source: bank list provided by Saiyam. 809 entries, 37 flagged as priority
// (major nationalised/private/small-finance banks) so they surface first in the
// picker before any search term is typed. Regenerate via the parsing script in
// docs/ if this list is ever updated with a fresh export.
const BANK_LIST = [
  { id: '16', name: 'State Bank of India (SBI)', priority: true },
  { id: '7', name: 'HDFC Bank Ltd', priority: true },
  { id: '8', name: 'ICICI Bank Ltd', priority: true },
  { id: '2', name: 'Axis Bank Ltd', priority: true },
  { id: '14', name: 'Punjab National Bank', priority: true },
  { id: '3', name: 'Bank of Baroda (BOB)', priority: true },
  { id: '5', name: 'Canara Bank', priority: true },
  { id: '19', name: 'Union Bank of India (UBI)', priority: true },
  { id: '4', name: 'Bank of India (BOI)', priority: true },
  { id: '11', name: 'Kotak Mahindra Bank Ltd', priority: true },
  { id: '10', name: 'IndusInd Bank Ltd', priority: true },
  { id: '9', name: 'IDBI Bank Limited', priority: true },
  { id: '23', name: 'Yes Bank', priority: true },
  { id: '6', name: 'Federal Bank Ltd', priority: true },
  { id: '24', name: 'IDFC First Bank Ltd', priority: true },
  { id: '36', name: 'Bandhan Bank', priority: true },
  { id: '25', name: 'Central Bank of India (CBI)', priority: true },
  { id: '57', name: 'UCO Bank', priority: true },
  { id: '64', name: 'Indian Overseas Bank', priority: true },
  { id: '70', name: 'Punjab and Sind Bank', priority: true },
  { id: '37', name: 'Bank of Maharashtra', priority: true },
  { id: '22', name: 'Indian Bank', priority: true },
  { id: '41', name: 'RBL Bank', priority: true },
  { id: '40', name: 'AU Small Finance Bank', priority: true },
  { id: '49', name: 'South Indian Bank', priority: true },
  { id: '51', name: 'Karnataka Bank', priority: true },
  { id: '100', name: 'Karur Vysya Bank', priority: true },
  { id: '58', name: 'City Union Bank', priority: true },
  { id: '34', name: 'DCB Bank Limited', priority: true },
  { id: '61', name: 'Equitas Small Finance Bank', priority: true },
  { id: '142', name: 'ESAF Small Finance Bank', priority: true },
  { id: '42', name: 'Jana Small Finance Bank', priority: true },
  { id: '59', name: 'Suryoday Small Finance Bank Limited', priority: true },
  { id: '46', name: 'Tamilnad Mercantile Bank Ltd', priority: true },
  { id: '86', name: 'CSB Bank', priority: true },
  { id: '43', name: 'Dhanlaxmi Bank Ltd', priority: true },
  { id: '263', name: 'The Nainital Bank Ltd', priority: true },
  { id: '692', name: 'Abasaheb Patil Rendal Sahakari Bank Ltd', priority: false },
  { id: '474', name: 'Abhinandan Urban Co.op Bank Ltd', priority: false },
  { id: '105', name: 'Abhyudaya Co-Operative Bank Ltd', priority: false },
  { id: '524', name: 'Adarniya P. D. Patilsaheb Sahakari Bank Ltd.', priority: false },
  { id: '62', name: 'Adarsh Co-op Bank Ltd', priority: false },
  { id: '278', name: 'Adarsh Mahila Mercantile Co-op Bank Ltd', priority: false },
  { id: '191', name: 'Ahmednagar Merchant\'s Co-operative Bank Ltd', priority: false },
  { id: '475', name: 'Ahmednagar Sahar Sahakari Bank Ltd', priority: false },
  { id: '138', name: 'Airtel Payments Bank', priority: false },
  { id: '1', name: 'Akhand Anand Co-Operative Bank Ltd', priority: false },
  { id: '680', name: 'Alavi Co-Operative Bank Ltd', priority: false },
  { id: '573', name: 'Alibag Urban Co. Op. Bank Ltd.', priority: false },
  { id: '206', name: 'Almora Urban Co-Operative Bank Ltd', priority: false },
  { id: '279', name: 'Aman Sahakari Bank Ltd', priority: false },
  { id: '280', name: 'Ambajogai Peoples Co-op Bank Ltd', priority: false },
  { id: '374', name: 'Ambarnath Jai Hind Co Op Bank Ltd', priority: false },
  { id: '771', name: 'Amreli Nagrik Sahkari Bank Ltd.', priority: false },
  { id: '384', name: 'Andhra Bank', priority: false },
  { id: '649', name: 'Andhra Pradesh Grameena Bank', priority: false },
  { id: '283', name: 'Andhra Pradesh Grameena Vikas Bank', priority: false },
  { id: '139', name: 'Andhra Pradesh Mahesh Co-Operative Urban Bank Ltd', priority: false },
  { id: '207', name: 'Andhra Pragathi Grameena Bank', priority: false },
  { id: '383', name: 'Annasaheb Magar Sahakari Bank', priority: false },
  { id: '667', name: 'Anuradha Urban Co-Operative.Bank Ltd', priority: false },
  { id: '621', name: 'Apani Sahakari Bank Ltd', priority: false },
  { id: '144', name: 'Apna Sahakari Bank Ltd', priority: false },
  { id: '575', name: 'Appasaheb Birnale Sahakari Bank Ltd', priority: false },
  { id: '625', name: 'Arunachal Pradesh Rural Bank', priority: false },
  { id: '424', name: 'Arvind Sahakari Bank Ltd', priority: false },
  { id: '423', name: 'Ashok Nagri Sahakari Bank Ltd', priority: false },
  { id: '534', name: 'Ashok Sahakari Bank Ltd', priority: false },
  { id: '792', name: 'Ashokanagar Co-Operative Bank Ltd.', priority: false },
  { id: '615', name: 'Assam Gramin Vikas Bank', priority: false },
  { id: '28', name: 'Associate Co-Operative Bank Ltd', priority: false },
  { id: '490', name: 'Balasinor Nagarik Sahakari Bank Ltd.', priority: false },
  { id: '378', name: 'Balotra Urban Co-Operative Bank', priority: false },
  { id: '440', name: 'Bangiya Gramin Vikash Bank', priority: false },
  { id: '816', name: 'Bank of Bahrain and Kuwait', priority: false },
  { id: '343', name: 'Bank of Bhutan', priority: false },
  { id: '774', name: 'Bapuji Co-operative Bank Ltd.', priority: false },
  { id: '781', name: 'Baran Nagrik Sahakari Bank Ltd.', priority: false },
  { id: '345', name: 'Barclays Bank', priority: false },
  { id: '38', name: 'Baroda Gujarat Gramin Bank', priority: false },
  { id: '125', name: 'Baroda Rajasthan Kshetriya Gramin Bank', priority: false },
  { id: '185', name: 'Baroda UP Bank', priority: false },
  { id: '94', name: 'Bassein Catholic Co-Operative Bank Ltd', priority: false },
  { id: '433', name: 'Beawar Urban Co-operative Bank Ltd', priority: false },
  { id: '638', name: 'Belagavi Shree Basaveshwar Co-op Bank Ltd', priority: false },
  { id: '420', name: 'Bellad-Bagewadi Urban Souharda Sahakari Bank Ltd', priority: false },
  { id: '589', name: 'Bhadohi Urban Co.op Bank Ltd', priority: false },
  { id: '284', name: 'Bhadradri Co-operative Urban Bank Ltd', priority: false },
  { id: '485', name: 'Bhagini Nivedita Sahakari Bank Ltd', priority: false },
  { id: '66', name: 'Bharat Co-Op bank Ltd', priority: false },
  { id: '352', name: 'Bharati Sahakari Bank', priority: false },
  { id: '402', name: 'Bharuch District Central Co-operative Bank', priority: false },
  { id: '755', name: 'Bhausaheb Birajdar Urban Co-Oprative Bank', priority: false },
  { id: '580', name: 'Bhausaheb Sahakari Bank Ltd', priority: false },
  { id: '536', name: 'Bhavana Rishi Co-op Urban Bank Ltd', priority: false },
  { id: '141', name: 'Bhavsar Nagari Sahakari Patsanstha Ltd', priority: false },
  { id: '544', name: 'Bhingar Urban Co-op Bank Ltd', priority: false },
  { id: '137', name: 'Bombay Mercantile Co-operative Bank Ltd', priority: false },
  { id: '658', name: 'Brahmadeodada Mane Sahakari Bank Ltd', priority: false },
  { id: '779', name: 'Bramhapuri Urban Co Op. Bank Ltd', priority: false },
  { id: '179', name: 'Capital Small Finance Bank', priority: false },
  { id: '493', name: 'Chaitanya Godavari Grameena Bank', priority: false },
  { id: '327', name: 'CHARTERED SAHAKARI BANK NIYAMITHA', priority: false },
  { id: '819', name: 'Chennai Central Co-Operative Bank', priority: false },
  { id: '707', name: 'Chhattisgarh Gramin Bank', priority: false },
  { id: '165', name: 'Chhattisgarh Rajya Gramin Bank', priority: false },
  { id: '147', name: 'Chittoor District Co Operative Central Bank', priority: false },
  { id: '381', name: 'Chittorgarh Kendriya Sahkari Bank Ltd', priority: false },
  { id: '328', name: 'Chittorgarh Urban Co-Operative Bank Ltd', priority: false },
  { id: '74', name: 'Citi Bank', priority: false },
  { id: '93', name: 'Citizencredit Co-Operative Bank Ltd', priority: false },
  { id: '31', name: 'Citizens Co-Operative Bank Ltd', priority: false },
  { id: '526', name: 'Coastal Local Area Bank Ltd', priority: false },
  { id: '462', name: 'Col RD Nikam Sainik Sahakari Bank Ltd', priority: false },
  { id: '101', name: 'Commonwealth Bank', priority: false },
  { id: '392', name: 'Contai Co-op Bank Ltd', priority: false },
  { id: '348', name: 'Credit Agricole Corporate & Investment Bank', priority: false },
  { id: '360', name: 'Daivadnya Sahakara Bank', priority: false },
  { id: '111', name: 'Dakshin Bihar Gramin Bank', priority: false },
  { id: '210', name: 'Dapoli Urban Co Operative Bank Ltd', priority: false },
  { id: '681', name: 'Darjeeling District Central Co Operative Bank', priority: false },
  { id: '449', name: 'Dausa Urban Cooperative Bank Ltd', priority: false },
  { id: '594', name: 'Davangere Urban Co-Op Bank Ltd.', priority: false },
  { id: '35', name: 'DBS Bank Ltd', priority: false },
  { id: '211', name: 'Deendayal Nagari Sahakari Bank Ltd', priority: false },
  { id: '608', name: 'Deepak shakari Bank Ltd.', priority: false },
  { id: '104', name: 'Deogiri Nagarik Sahakari Bank Ltd', priority: false },
  { id: '80', name: 'Deutsche Bank', priority: false },
  { id: '735', name: 'Development Co-operative Bank Ltd', priority: false },
  { id: '213', name: 'Dhanera Mercantile Co-Operative Bank Ltd', priority: false },
  { id: '697', name: 'Dharmavir Sambhaji Urban Co-Op Bank Ltd', priority: false },
  { id: '285', name: 'Dhule Vikas Sahakari Bank', priority: false },
  { id: '214', name: 'Diamond Trust Bank', priority: false },
  { id: '821', name: 'Dindigul Central Co-operative Bank Ltd.', priority: false },
  { id: '501', name: 'District Co-op Central Bank Ltd', priority: false },
  { id: '189', name: 'DMK Jaoli Bank', priority: false },
  { id: '810', name: 'Doha Bank', priority: false },
  { id: '172', name: 'Dombivli Nagari Sahakari Bank', priority: false },
  { id: '760', name: 'Dr. Annasaheb Chougule Urban Co-op. Bank Ltd', priority: false },
  { id: '627', name: 'Dr. Punjabrao Deshmukh Urban Co.Op Bank Ltd', priority: false },
  { id: '604', name: 'Durgapur Steel Peoples Co-Op Bank Ltd.', priority: false },
  { id: '455', name: 'Ellaquai Dehati Bank', priority: false },
  { id: '790', name: 'Emirates Islamic Bank', priority: false },
  { id: '796', name: 'Erode District Central Cooperative Bank', priority: false },
  { id: '286', name: 'Everest Bank Ltd', priority: false },
  { id: '56', name: 'Fincare Small Finance Bank', priority: false },
  { id: '96', name: 'Fingrowth Co-Operative Bank Ltd', priority: false },
  { id: '119', name: 'Fino Payments Bank', priority: false },
  { id: '815', name: 'First National Bank', priority: false },
  { id: '584', name: 'Gandhibag Sahakari Bank Ltd.', priority: false },
  { id: '162', name: 'Ganesh Co-operative Bank Ltd', priority: false },
  { id: '234', name: 'Godavari Laxmi Co Operative Bank Ltd', priority: false },
  { id: '287', name: 'Godavari Urban co-operative Bank Ltd', priority: false },
  { id: '607', name: 'Gondal Nagarik Sahakari Bank Ltd.', priority: false },
  { id: '83', name: 'GP Parsik Sahakari Bank Ltd', priority: false },
  { id: '97', name: 'GS Mahanagar Co-Operative Bank Ltd', priority: false },
  { id: '148', name: 'Guardian Souharda Sahakari Bank', priority: false },
  { id: '530', name: 'Gujarat Ambuja Co.op Bank', priority: false },
  { id: '676', name: 'Gujarat Gramin Bank', priority: false },
  { id: '826', name: 'Haryana Gramin Bank', priority: false },
  { id: '617', name: 'Haveli Sahakari Bank Ltd', priority: false },
  { id: '639', name: 'Himachal Pradesh Gramin Bank', priority: false },
  { id: '174', name: 'Himachal Pradesh State Co Operative Bank Ltd', priority: false },
  { id: '217', name: 'Himatnagar Nagrik Sahakari Bank Ltd', priority: false },
  { id: '77', name: 'HSBC Bank', priority: false },
  { id: '218', name: 'Hutatma Sahakari Bank Ltd', priority: false },
  { id: '156', name: 'India Post Payments Bank', priority: false },
  { id: '632', name: 'Indira Mahila Sahakari Bank Ltd', priority: false },
  { id: '219', name: 'Indore Cloth Market Co-operative Bank Ltd', priority: false },
  { id: '597', name: 'Indore Paraspar Sahakari Bank Ltd', priority: false },
  { id: '797', name: 'Indore Premier Co-operative Bank Ltd.', priority: false },
  { id: '288', name: 'Indraprastha Sehkari Bank Ltd', priority: false },
  { id: '332', name: 'Indrayani Co Op Bank Ltd', priority: false },
  { id: '379', name: 'Integral Urban Co-op Bank Ltd', priority: false },
  { id: '445', name: 'Irinjalakuda Town co-operative bank', priority: false },
  { id: '522', name: 'J & K Grameen Bank', priority: false },
  { id: '799', name: 'Jai Hindh Urban Co.op Bank Ltd.', priority: false },
  { id: '711', name: 'Jain Co-Operative Bank Ltd.', priority: false },
  { id: '149', name: 'Jalgaon Janta Sahakari Bank', priority: false },
  { id: '512', name: 'Jalore Nagrik Sahkari Bank Ltd', priority: false },
  { id: '115', name: 'Jamia Co-Operative Bank', priority: false },
  { id: '69', name: 'Jammu And Kashmir Bank Ltd (J&K BANK)', priority: false },
  { id: '481', name: 'Jamnagar Peoples Co Operative Bank', priority: false },
  { id: '199', name: 'Janakalyan Sahakari Bank Ltd', priority: false },
  { id: '132', name: 'Janaseva Sahakari Bank Ltd', priority: false },
  { id: '117', name: 'Janata Sahakari Bank Ltd', priority: false },
  { id: '784', name: 'Janata Urban Co-op Bank Ltd Wai', priority: false },
  { id: '587', name: 'Janatha Seva Co-operative Bank', priority: false },
  { id: '552', name: 'Jankalyan Co-Op. Bank Limited', priority: false },
  { id: '724', name: 'Jankalyan Urban Co Op Bank Ltd', priority: false },
  { id: '591', name: 'Janseva Co Operative Bank Ltd', priority: false },
  { id: '220', name: 'Janseva Urban Co Operative Bank Ltd', priority: false },
  { id: '831', name: 'Jath Urban Co-op. Bank Ltd.', priority: false },
  { id: '416', name: 'Jhalawar District Central Co op Bank', priority: false },
  { id: '170', name: 'Jharkhand Rajya Gramin Bank', priority: false },
  { id: '409', name: 'JIJAMATA MAHILA SAHAKARI BANK LTD', priority: false },
  { id: '338', name: 'Jijau Commercial Co-op Bank Ltd', priority: false },
  { id: '113', name: 'Jila Sahakari Kendriya Bank', priority: false },
  { id: '289', name: 'Jio Payments Bank Ltd', priority: false },
  { id: '653', name: 'Jivaji Sahakari Bank Ltd', priority: false },
  { id: '103', name: 'Jivan Commercial Co-Operative Bank Ltd', priority: false },
  { id: '635', name: 'Jodhpur Nagrik Sahakari Bank Ltd', priority: false },
  { id: '766', name: 'JP Morgan Chase Bank', priority: false },
  { id: '133', name: 'Kallappanna Awade Ichalkaranji Janata Sahakari Bank Ltd', priority: false },
  { id: '112', name: 'Kankaria Maninagar Nagrik Sahakari Bank Ltd', priority: false },
  { id: '221', name: 'Karimnagar District Co operative Central Bank Ltd', priority: false },
  { id: '155', name: 'Karnataka Gramin Bank', priority: false },
  { id: '143', name: 'Karnataka Vikas Grameena Bank', priority: false },
  { id: '662', name: 'Kashipur urban Co-Operative Bank', priority: false },
  { id: '470', name: 'Kerala Gramin Bank', priority: false },
  { id: '663', name: 'Kerala State Co-Op. Bank Ltd.', priority: false },
  { id: '661', name: 'Keshav Sehkari Bank Ltd', priority: false },
  { id: '633', name: 'Kodagu District co-operative Bank', priority: false },
  { id: '620', name: 'Kohinoor Sahakari Bank Ltd', priority: false },
  { id: '764', name: 'Koilkuntla CO-Operative Bank Limited.', priority: false },
  { id: '290', name: 'Kokan Bank', priority: false },
  { id: '216', name: 'Kokan Mercantile Co-operative Bank Ltd', priority: false },
  { id: '222', name: 'Kolhapur District Central Co-op Bank Ltd', priority: false },
  { id: '291', name: 'Kolhapur Mahila Sahakari Bank Ltd', priority: false },
  { id: '292', name: 'Kopargaon People\'s Co op Bank Ltd', priority: false },
  { id: '757', name: 'Koteshwara Sahakari Bank Niyamitha', priority: false },
  { id: '447', name: 'Koyana Sahakari Bank Ltd', priority: false },
  { id: '606', name: 'Krishna Bhima Samruddhi Local Area Bank', priority: false },
  { id: '683', name: 'Krishna District Co-operative Central Bank', priority: false },
  { id: '818', name: 'Krishna Mercantile Co-Operative Bank Ltd.', priority: false },
  { id: '380', name: 'Krishna Sahakari Bank Ltd', priority: false },
  { id: '389', name: 'Kumari Bank Ltd', priority: false },
  { id: '837', name: 'L & T Finance', priority: false },
  { id: '477', name: 'LALA URBAN CO-OP BANK LTD', priority: false },
  { id: '630', name: 'Latur District Central Co-Op Bank Ltd.', priority: false },
  { id: '834', name: 'Laxmi Mahila Nagrik Sahkari Bank Maryadit', priority: false },
  { id: '140', name: 'Laxmi Sunrise Bank', priority: false },
  { id: '223', name: 'Laxmi Urban Co-operative Bank Ltd', priority: false },
  { id: '434', name: 'Lokmangal Co-Op Bank Ltd', priority: false },
  { id: '334', name: 'Loknete Dattaji Patil Sahkari Bank', priority: false },
  { id: '548', name: 'Lokvikas Nagari Sahakari Bank Ltd', priority: false },
  { id: '212', name: 'Lonawala Sahakari Bank', priority: false },
  { id: '793', name: 'M D pawar peoples co-operative bank', priority: false },
  { id: '224', name: 'M S Co Operative Bank Ltd', priority: false },
  { id: '763', name: 'M&T Bank', priority: false },
  { id: '476', name: 'Madhya Pradesh Gramin Bank', priority: false },
  { id: '593', name: 'Madhya Pradesh State Co-op Bank Ltd', priority: false },
  { id: '201', name: 'Madhyanchal Gramin Bank', priority: false },
  { id: '309', name: 'Mahanagar Nagrik Sahakari Bank', priority: false },
  { id: '762', name: 'Maharana Pratap Co-Operative Urban Bank Ltd.', priority: false },
  { id: '134', name: 'Maharashtra Gramin Bank', priority: false },
  { id: '439', name: 'Mahatma Fule Bank', priority: false },
  { id: '427', name: 'Mahesh Sahakari bank Ltd', priority: false },
  { id: '194', name: 'Mahesh Urban Co operative Bank', priority: false },
  { id: '811', name: 'Mahila Nagrik Sahakari Bank Maryadit', priority: false },
  { id: '369', name: 'Makarpura Indutrial Estate Co-op Bank Ltd', priority: false },
  { id: '583', name: 'Malda District Central Co.op Bank', priority: false },
  { id: '458', name: 'Malviya Urban Co-op Bank Ltd', priority: false },
  { id: '686', name: 'Mandya District Co-op Central Bank Ltd', priority: false },
  { id: '728', name: 'Mangal Co-Operative Bank Ltd.', priority: false },
  { id: '293', name: 'Maninagar Co-operative Bank Ltd', priority: false },
  { id: '640', name: 'Manjeri Co-Operative Urban Bank LTD', priority: false },
  { id: '626', name: 'Mann Deshi Mahila Sahakari Bank Ltd.', priority: false },
  { id: '624', name: 'Manorama Co.op Bank Ltd', priority: false },
  { id: '732', name: 'Mansing Co-operative Bank Ltd.', priority: false },
  { id: '294', name: 'Manvi Pattana Souharda Sahakari Bank', priority: false },
  { id: '612', name: 'Maratha Co-Operative Bank Ltd', priority: false },
  { id: '533', name: 'Markandey Nagari Sahakari Bank Ltd.', priority: false },
  { id: '414', name: 'Marketyard Commercial Co-Op Bank Ltd', priority: false },
  { id: '835', name: 'Mashreq Bank', priority: false },
  { id: '808', name: 'Meghalaya Rural Bank', priority: false },
  { id: '425', name: 'Merchants Liberal Co-op Bank Ltd', priority: false },
  { id: '421', name: 'Midland Bank', priority: false },
  { id: '448', name: 'Mizoram Rural Bank', priority: false },
  { id: '160', name: 'Model Co-operative Bank Ltd', priority: false },
  { id: '124', name: 'Motiram Agrawal Jalna Merchants Co-op Bank Ltd', priority: false },
  { id: '701', name: 'Mount Nagrik Sahakari Bank Ltd.', priority: false },
  { id: '442', name: 'MUFG Bank Ltd', priority: false },
  { id: '431', name: 'Mumbai District Central Co-op Bank Ltd', priority: false },
  { id: '465', name: 'NAGAR SAHKARI BANK LTD', priority: false },
  { id: '531', name: 'Nagarik Sahakari Bank Ltd', priority: false },
  { id: '399', name: 'Nagnath Urban Co-op Bank Ltd', priority: false },
  { id: '225', name: 'Nagpur Nagarik Sahakari Bank Ltd', priority: false },
  { id: '682', name: 'Nagrik Sahakari Bank Maryadit Gwalior', priority: false },
  { id: '558', name: 'Nagrik Sahakari Bank Maryadit Vidisha', priority: false },
  { id: '226', name: 'Nandani Sahakari Bank Ltd', priority: false },
  { id: '809', name: 'Nashik District Central Co-op Bank Ltd.', priority: false },
  { id: '181', name: 'Nasik Merchants Co-Op Bank Ltd', priority: false },
  { id: '397', name: 'National Urban Co Operative Bank', priority: false },
  { id: '296', name: 'Nav Jeevan Co-op Bank Ltd', priority: false },
  { id: '444', name: 'Navanagar Urban Co.op Bank Ltd', priority: false },
  { id: '722', name: 'Navapur Mercantile Co-operative Bank Ltd', priority: false },
  { id: '108', name: 'Navi Mumbai Co-Operative Bank Ltd', priority: false },
  { id: '176', name: 'Navsarjan Industrial Co Operative Bank Ltd', priority: false },
  { id: '768', name: 'Neelkanth Co-Op Bank Ltd.', priority: false },
  { id: '418', name: 'Nepal Investment Mega Bank Ltd', priority: false },
  { id: '45', name: 'New India co-operative Bank Ltd', priority: false },
  { id: '177', name: 'Nidhi Co-Operative Bank Ltd', priority: false },
  { id: '370', name: 'Nilambur Co-operative Urban Bank', priority: false },
  { id: '484', name: 'Nirmal Urban Co-Op Bank Ltd', priority: false },
  { id: '54', name: 'NKGSB Co-op Bank Ltd', priority: false },
  { id: '705', name: 'Noida Commercial Co-op Bank Ltd', priority: false },
  { id: '741', name: 'NongHyup Bank', priority: false },
  { id: '227', name: 'North East Small Finance Bank', priority: false },
  { id: '466', name: 'NSDL Payments Bank', priority: false },
  { id: '123', name: 'Nutan Nagarik Sahakari Bank Ltd', priority: false },
  { id: '650', name: 'Odisha Grameen Bank', priority: false },
  { id: '400', name: 'Odisha Gramya Bank', priority: false },
  { id: '775', name: 'Omerga Janata Sahakari Bank Ltd.', priority: false },
  { id: '171', name: 'Omprakash Deora Peoples Co-Operative Bank', priority: false },
  { id: '228', name: 'Padmavathi Co Op Urban Bank Ltd', priority: false },
  { id: '752', name: 'Padra Nagar Nagrik Sahakari Bank Ltd', priority: false },
  { id: '507', name: 'Pali Urban Co.op Bank Ltd', priority: false },
  { id: '535', name: 'Palus Sahakari Bank Ltd', priority: false },
  { id: '556', name: 'Parshwanath Co-op. Bank Ltd', priority: false },
  { id: '689', name: 'Patan Co. Op. Bank Ltd', priority: false },
  { id: '539', name: 'Patan Nagarik Sahakari Bank Ltd.', priority: false },
  { id: '298', name: 'Pavana Sahakari Bank Ltd', priority: false },
  { id: '13', name: 'Paytm Payments Bank Ltd', priority: false },
  { id: '588', name: 'People\'s Co-operative Bank Ltd', priority: false },
  { id: '394', name: 'Pimpri Chinchwad Sahakari Bank', priority: false },
  { id: '651', name: 'Pochampally Co.op Urban Bank Ltd', priority: false },
  { id: '838', name: 'Poonawalla Fincorp', priority: false },
  { id: '236', name: 'Poornawadi Nagrik Sahakari Bank', priority: false },
  { id: '537', name: 'Pragathi Co-op Bank Ltd.', priority: false },
  { id: '346', name: 'Pragati Sahakari Bank Ltd', priority: false },
  { id: '376', name: 'Prathama UP Gramin Bank', priority: false },
  { id: '145', name: 'Pravara Sahakari Bank Ltd', priority: false },
  { id: '299', name: 'Prerana Co-op Bank Ltd', priority: false },
  { id: '27', name: 'Prime Co Op Bank', priority: false },
  { id: '806', name: 'Priyadarshani Mahila Nagari Sahkari Bank LTD.', priority: false },
  { id: '422', name: 'Priyadarshani Nagari Sahakari Bank Ltd', priority: false },
  { id: '786', name: 'Priyadarshani Urban Co.op Bank Ltd.', priority: false },
  { id: '595', name: 'Progressive Co-operative Bank Ltd', priority: false },
  { id: '130', name: 'Progressive Mercantile Co Operative Bank Ltd', priority: false },
  { id: '229', name: 'Progressive Urban Co-operative Bank', priority: false },
  { id: '388', name: 'Pune Cantonment Sahakari Bank Ltd', priority: false },
  { id: '169', name: 'Pune District Central Co-Operative Bank Ltd', priority: false },
  { id: '800', name: 'Pune Merchant\'s Co-Op Bank Ltd', priority: false },
  { id: '778', name: 'Pune Municipal Corporation Servants Co-op Urban Bank Ltd', priority: false },
  { id: '230', name: 'Pune Peoples Co Operative Bank', priority: false },
  { id: '495', name: 'Pune Urban Co-op Bank Ltd', priority: false },
  { id: '488', name: 'Punjab Gramin Bank', priority: false },
  { id: '483', name: 'Pusad Urban Co Operative Bank Ltd', priority: false },
  { id: '813', name: 'Rahimatpur Sahakari Bank Ltd.', priority: false },
  { id: '785', name: 'Raigad District Central Co-Operative Bank Ltd.', priority: false },
  { id: '454', name: 'Raiganj Central Co-Operative Bank Ltd.', priority: false },
  { id: '582', name: 'Rajadhani Co-operative Urban Bank Ltd', priority: false },
  { id: '616', name: 'Rajapur Urban Co-operative Bank', priority: false },
  { id: '157', name: 'Rajarambapu Sahakari Bank Ltd', priority: false },
  { id: '204', name: 'Rajarshi Shahu Sahakari Bank', priority: false },
  { id: '704', name: 'Rajasthan Gramin Bank', priority: false },
  { id: '98', name: 'Rajasthan Marudhara Gramin Bank', priority: false },
  { id: '678', name: 'Rajdhani Nagar Sahkari Bank Ltd', priority: false },
  { id: '135', name: 'Rajgurunagar Sahakari Bank Ltd', priority: false },
  { id: '32', name: 'Rajkot Nagarik Sahakari Bank Ltd', priority: false },
  { id: '72', name: 'Rajkot Peoples Co-operative Bank Ltd', priority: false },
  { id: '541', name: 'Rajlaxmi Urban Co.op Bank Ltd.', priority: false },
  { id: '772', name: 'RAK Bank', priority: false },
  { id: '699', name: 'Ramrajya Sahakari Bank Ltd', priority: false },
  { id: '574', name: 'Rastriya Banijya Bank', priority: false },
  { id: '770', name: 'Ratanchand Shah Co-Op Bank Ltd.', priority: false },
  { id: '567', name: 'Ratnagiri District Central Co.op Bank Ltd', priority: false },
  { id: '659', name: 'Repco Bank', priority: false },
  { id: '795', name: 'Riyad Bank', priority: false },
  { id: '721', name: 'Royal Bank Of Canada', priority: false },
  { id: '643', name: 'Sadalga Urban Souharda Sahakari Bank', priority: false },
  { id: '497', name: 'Sadguru Nagrik Sahakari Bank', priority: false },
  { id: '128', name: 'Sadhana Sahakari Bank Ltd', priority: false },
  { id: '353', name: 'Saibaba Nagari Sahakari Bank', priority: false },
  { id: '231', name: 'Samarth Sahakari Bank Ltd', priority: false },
  { id: '674', name: 'Samata Co-operative Development Bank Ltd', priority: false },
  { id: '232', name: 'Samata Sahakari Bank Ltd', priority: false },
  { id: '783', name: 'Sambalpur Dist. Co-Op. Central Bank Ltd.', priority: false },
  { id: '452', name: 'Sampada Sahakari Bank Ltd', priority: false },
  { id: '733', name: 'Samruddhi Co-op Bank Ltd', priority: false },
  { id: '233', name: 'Sandur Pattana Souharda Sahakari Bank', priority: false },
  { id: '300', name: 'Sangli District Central Co-Op Bank Ltd', priority: false },
  { id: '428', name: 'Sangli Urban Co-operative Bank Ltd', priority: false },
  { id: '237', name: 'Sangola Urban Co Operative Bank Ltd', priority: false },
  { id: '506', name: 'Sanmati Sahakari Bank Ltd.', priority: false },
  { id: '824', name: 'Sanmitra Mahila Nagari Sahakari Bank Maryadit, Chandrapur', priority: false },
  { id: '788', name: 'Sanmitra Sahakari Bank Ltd.', priority: false },
  { id: '215', name: 'Sant Sopankaka Sahakari Bank Ltd', priority: false },
  { id: '67', name: 'Santander Bank', priority: false },
  { id: '120', name: 'Saraspur Nagrik Co-Operative Bank Ltd', priority: false },
  { id: '21', name: 'Saraswat co-op Bank Ltd', priority: false },
  { id: '675', name: 'Sardar Singh Nagrik Sahkari Bank', priority: false },
  { id: '159', name: 'Sardar Vallabhbhai Sahakari Bank Ltd', priority: false },
  { id: '390', name: 'Sardarganj Mercantile Co op Bank Ltd', priority: false },
  { id: '365', name: 'Sarva Haryana Gramin Bank', priority: false },
  { id: '301', name: 'Sarvodaya Commercial Co op Bank Ltd', priority: false },
  { id: '121', name: 'Sarvodaya Nagarik Sahakari Bank Ltd', priority: false },
  { id: '79', name: 'Saurashtra Gramin Bank', priority: false },
  { id: '543', name: 'Sawai Madhopur Urban Co-Operative Bank Ltd.', priority: false },
  { id: '44', name: 'SBM Bank', priority: false },
  { id: '342', name: 'SBPP Co-operative Bank Ltd.', priority: false },
  { id: '739', name: 'Scotiabank', priority: false },
  { id: '703', name: 'Shalini Sahakari Bank Ltd', priority: false },
  { id: '441', name: 'Shankar Nagari Sahakari Bank Ltd', priority: false },
  { id: '188', name: 'Sharad Sahakari Bank Ltd', priority: false },
  { id: '631', name: 'Shihori Nagrik Sahkari Bank Ltd', priority: false },
  { id: '90', name: 'Shikshak Sahakari Bank Ltd', priority: false },
  { id: '655', name: 'Shimoga District Co-op Central Bank Ltd', priority: false },
  { id: '239', name: 'Shinhan Bank Of India', priority: false },
  { id: '613', name: 'Shiva Sahakari Bank', priority: false },
  { id: '657', name: 'Shivaji Nagari Sahakari Bank Ltd', priority: false },
  { id: '78', name: 'Shivalik Small Finance Bank', priority: false },
  { id: '336', name: 'Shivdaulat Sahakari Bank', priority: false },
  { id: '761', name: 'Shivkrupa Sahakari Patpedhi Ltd.', priority: false },
  { id: '357', name: 'Shivshakti Urban Co-Op Bank', priority: false },
  { id: '175', name: 'Shree Balaji Urban Co-operative Bank Ltd', priority: false },
  { id: '769', name: 'Shree Bharat Co-Operative Bank Ltd.', priority: false },
  { id: '89', name: 'Shree Chatrapati Shivaji Maharaj Sahakari Bank Niyamith', priority: false },
  { id: '349', name: 'Shree Co-Operative Bank Ltd', priority: false },
  { id: '398', name: 'Shree Dharati Co op Bank Ltd', priority: false },
  { id: '240', name: 'Shree Kadi Nagarik Sahakari Bank Ltd', priority: false },
  { id: '331', name: 'Shree Laxmi Co Op Bank', priority: false },
  { id: '489', name: 'Shree Mahalaxmi Urban Co.op Credit Bank Ltd', priority: false },
  { id: '432', name: 'Shree Mahavir Sahakari Bank Ltd', priority: false },
  { id: '302', name: 'Shree Mahesh Co-Op Bank Ltd', priority: false },
  { id: '337', name: 'Shree Samarth Sahakari Bank Ltd', priority: false },
  { id: '664', name: 'Shree Vardhman Sahakari Bank Ltd', priority: false },
  { id: '356', name: 'Shree Warana Sahakari Bank Ltd', priority: false },
  { id: '546', name: 'Shri Adinath Co-op Bank Ltd.', priority: false },
  { id: '823', name: 'Shri Agrasen Co-Operative Bank', priority: false },
  { id: '758', name: 'Shri Anand Nagari Sahakari Bank Ltd.', priority: false },
  { id: '196', name: 'Shri Arihant Co-operative Bank Ltd', priority: false },
  { id: '599', name: 'Shri Bharat Urban Co.op Bank Ltd', priority: false },
  { id: '114', name: 'Shri Chhatrapati Rajarshi Shahu Urban Co-Operative Bank Ltd', priority: false },
  { id: '729', name: 'Shri Gajanan Lokseva Sahakari Bank Maryadit', priority: false },
  { id: '303', name: 'Shri Gajanan Maharaj Urban Co op Bank Ltd', priority: false },
  { id: '730', name: 'Shri Gajanan Nagari Sahakari Bank Ltd', priority: false },
  { id: '429', name: 'SHRI GANESH SAHAKARI BANK LTD', priority: false },
  { id: '572', name: 'Shri Janata Sahakari Bank Ltd', priority: false },
  { id: '205', name: 'Shri Kanyaka Nagri Sahakari Bank Ltd', priority: false },
  { id: '508', name: 'Shri Krishna Co.op Bank Ltd', priority: false },
  { id: '569', name: 'Shri Laxmikrupa Urban Co Op Bank Ltd', priority: false },
  { id: '413', name: 'Shri Mahalaxmi Co-Op Bank Ltd', priority: false },
  { id: '499', name: 'Shri Mahavir Urban Co-Op Bank Ltd', priority: false },
  { id: '304', name: 'Shri Panchganga Nagari Sahakari Bank Ltd', priority: false },
  { id: '65', name: 'Shri Rajkot District Co-op Bank Ltd', priority: false },
  { id: '812', name: 'Shri Shantappanna Miraji Urban Co.op Bank Ltd.', priority: false },
  { id: '498', name: 'Shri Shiddeshwar Co.op Bank Ltd', priority: false },
  { id: '528', name: 'Shri Shiveshwar Nagri Sahakari Bank', priority: false },
  { id: '747', name: 'Shri Swami Samarth Sahakari Bank Ltd.', priority: false },
  { id: '178', name: 'Shri Veershaiv Co-Op Bank Ltd', priority: false },
  { id: '600', name: 'Shri Vinayak Sahakari Bank Ltd', priority: false },
  { id: '578', name: 'Shri. D. T. Patil Co-Op Bank Ltd.', priority: false },
  { id: '610', name: 'Shrimant Malojiraje Sahakari Bank Ltd.', priority: false },
  { id: '742', name: 'Shriram Urban Co-op Bank Ltd', priority: false },
  { id: '520', name: 'Siddeshwar Urban Co-op Bank', priority: false },
  { id: '241', name: 'Siddhartha Bank', priority: false },
  { id: '684', name: 'Siddheshwar Sahakari Bank Ltd', priority: false },
  { id: '665', name: 'Sihor Mercantile Co.op Bank Ltd.', priority: false },
  { id: '102', name: 'Sihor Nagarik Sahakari Bank Ltd', priority: false },
  { id: '350', name: 'Sikar Kendriya Saha Bank Ltd', priority: false },
  { id: '611', name: 'Sindhudurg District Central Co-Op Bank Ltd.', priority: false },
  { id: '803', name: 'Sindhudurg Sahakari Bank Ltd.', priority: false },
  { id: '753', name: 'Sir M Vishweshwaraiah Sahakar Bank', priority: false },
  { id: '710', name: 'Slice Small Finance Bank', priority: false },
  { id: '391', name: 'Smriti Nagrik Sahakari Bank', priority: false },
  { id: '122', name: 'Solapur Janata Sahakari Bank Ltd', priority: false },
  { id: '127', name: 'Solapur Siddheshwar Sahakari Bank Ltd', priority: false },
  { id: '82', name: 'Sree Charan Souhardha Co-Operative Bank Ltd', priority: false },
  { id: '622', name: 'Sree Subramanyeshwara Co.Op Bank Ltd', priority: false },
  { id: '563', name: 'Sree Thyagaraja Co-Operative Bank Ltd', priority: false },
  { id: '656', name: 'Sreenidhi Souharda Sahakari Bank', priority: false },
  { id: '415', name: 'SRI BASAVESHWAR SAHAKARI BANK', priority: false },
  { id: '565', name: 'Sri Gokarnanath Co-operative Bank Ltd.', priority: false },
  { id: '305', name: 'Sri Kanika Parameshwari Co Op Bank Ltd', priority: false },
  { id: '646', name: 'Sri Vasavamba Co-Operative Bank Ltd', priority: false },
  { id: '814', name: 'Standard Bank', priority: false },
  { id: '68', name: 'Standard Chartered Bank', priority: false },
  { id: '822', name: 'Standard Urban Co-Operative Bank', priority: false },
  { id: '767', name: 'State Transport CO-OP Bank Ltd.', priority: false },
  { id: '529', name: 'Sterling Urban Co-Op. Bank Ltd', priority: false },
  { id: '163', name: 'Suco Souharda Sahakari Bank Ltd', priority: false },
  { id: '691', name: 'Sulaimani Co-op Bank Ltd.', priority: false },
  { id: '173', name: 'Sundarlal Sawji urban Co-operative Bank', priority: false },
  { id: '29', name: 'Surat National Co-op Bank Ltd', priority: false },
  { id: '306', name: 'Suvarnayug Sahakari Bank Ltd', priority: false },
  { id: '95', name: 'SVC Co-Operative Bank Ltd', priority: false },
  { id: '787', name: 'Tamil Nadu Grama Bank', priority: false },
  { id: '746', name: 'Tamluk Ghatal Central Co-op Bank Ltd', priority: false },
  { id: '129', name: 'Telangana Grameena Bank', priority: false },
  { id: '152', name: 'Telangana State Co-Operative Apex Bank Limited', priority: false },
  { id: '647', name: 'Textile Co-Operative Bank Ltd', priority: false },
  { id: '50', name: 'Thane Bharat Sahakari Bank', priority: false },
  { id: '307', name: 'The Abhinav Sahakari Bank Ltd', priority: false },
  { id: '464', name: 'The Adarsh Co-Operative Urban Bank Limited', priority: false },
  { id: '55', name: 'The Adinath Co Op Bank Ltd', priority: false },
  { id: '372', name: 'The Agrasen Cooperative Urban Bank Ltd', priority: false },
  { id: '510', name: 'The Agrasen Nagari Sahakari Bank Ltd', priority: false },
  { id: '75', name: 'The Ahmedabad District Co-op Bank Ltd', priority: false },
  { id: '26', name: 'The Ahmedabad Mercantile Co-op Bank Ltd', priority: false },
  { id: '571', name: 'The Ahmednagar District Central Co-operative Bank Ltd.', priority: false },
  { id: '596', name: 'The Ajara Urban Co.Op. Bank Ltd', priority: false },
  { id: '187', name: 'The Akola Janata Commercial Co-operative Bank Ltd', priority: false },
  { id: '183', name: 'The Akola Urban Co-Operative Bank Ltd', priority: false },
  { id: '242', name: 'The Akola-Washim District Central Co-op Bank Ltd', priority: false },
  { id: '363', name: 'The Ambika Mahila Sahakari Bank Ltd', priority: false },
  { id: '73', name: 'The Amreli Jilla Madhyastha Sahakari Bank Ltd', priority: false },
  { id: '517', name: 'The Anand Mercantile Co-Operative Bank Ltd', priority: false },
  { id: '700', name: 'The Andhra Pradesh State Co-Operative Bank Ltd.', priority: false },
  { id: '521', name: 'The Annasaheb Savant Cooperative Urban Bank Mahad Ltd', priority: false },
  { id: '375', name: 'The Ashta Peoples Co-Operative Bank Ltd', priority: false },
  { id: '634', name: 'The Azad Co-op Bank Ltd', priority: false },
  { id: '243', name: 'The Babasaheb Deshmukh Sahakari Bank Ltd', priority: false },
  { id: '687', name: 'The Bagalkot District Central Co-Ope Bank Ltd', priority: false },
  { id: '308', name: 'The Bailhongal Urban Co Op Bank Ltd', priority: false },
  { id: '208', name: 'The Banaskantha District Central Co op Bank Ltd', priority: false },
  { id: '146', name: 'The Banaskantha Mercantile Co Operative Bank', priority: false },
  { id: '668', name: 'The Bangalore City Co-Op Bank Ltd', priority: false },
  { id: '641', name: 'The Bapunagar Mahila Co-Op. Bank Ltd', priority: false },
  { id: '244', name: 'The Baramati Sahakari Bank Ltd', priority: false },
  { id: '245', name: 'The Bardoli Nagrik Sahakari Bank Ltd', priority: false },
  { id: '362', name: 'The Barmer Central Co-operative Bank', priority: false },
  { id: '92', name: 'The Baroda Central Co-Operative Bank Ltd', priority: false },
  { id: '479', name: 'The Barodacity Co-Operative Bank Ltd', priority: false },
  { id: '246', name: 'The Bavla Nagarik Sahakari Bank Ltd', priority: false },
  { id: '518', name: 'The Bellary District Co-Operative Central Bank Ltd', priority: false },
  { id: '358', name: 'The Bhagyalaxshmi Mahila Sahakari Bank Ltd', priority: false },
  { id: '480', name: 'The Bhagyodaya Co-Operative Bank Ltd', priority: false },
  { id: '547', name: 'The Bhandara Urban Co-Operative Bank Ltd.', priority: false },
  { id: '84', name: 'The Bhavnagar District Co-operative Bank Ltd', priority: false },
  { id: '515', name: 'The Bhuj Commercial Co-Op Bank Ltd.', priority: false },
  { id: '247', name: 'The Bhuj Mercantile Co Operative Bank Ltd', priority: false },
  { id: '386', name: 'The Bicholim Urban Co-Operative Bank Ltd', priority: false },
  { id: '538', name: 'The Bijnor Urban Co.op Bank Ltd', priority: false },
  { id: '555', name: 'The Burdwan Central Co-operative Bank Ltd', priority: false },
  { id: '494', name: 'The Business Co-op Bank Limited', priority: false },
  { id: '693', name: 'The Calicut Town Service Co-operative Bank Ltd', priority: false },
  { id: '798', name: 'The Central Co-operative Bank Ltd.', priority: false },
  { id: '351', name: 'The Chanasma Commercial Co-Operative Bank Ltd', priority: false },
  { id: '562', name: 'The Chanasma Nagrik Sahakari Bank Ltd.', priority: false },
  { id: '366', name: 'The Chandrapur District Central Co-Operative Bank', priority: false },
  { id: '666', name: 'The Chandwad Merchant\'s Co.op Bank Ltd', priority: false },
  { id: '467', name: 'The Chembur Nagarik Sahakari Bank', priority: false },
  { id: '473', name: 'The Chhapi Nagrik Sahakari Bank Ltd', priority: false },
  { id: '248', name: 'The Chikhli Urban Co Operative Bank Ltd', priority: false },
  { id: '577', name: 'The Chiplun Urban Co-Operative Bank Ltd.', priority: false },
  { id: '249', name: 'The Chitnavispura Sahakari Bank Limited', priority: false },
  { id: '410', name: 'The Chopda People\'s Co.Op. Bank Ltd.', priority: false },
  { id: '669', name: 'The Co operative City Bank Ltd.', priority: false },
  { id: '250', name: 'The Co-op Bank of Mehsana Ltd', priority: false },
  { id: '126', name: 'The Co-Operative Bank of Rajkot Ltd', priority: false },
  { id: '310', name: 'The Commercial Co-op Bank ltd', priority: false },
  { id: '654', name: 'The Comptrollers Office Co.op Bank Ltd', priority: false },
  { id: '60', name: 'The Cosmos Co-op Bank Ltd', priority: false },
  { id: '804', name: 'The Dahanu Road Janta Co-Op Bank', priority: false },
  { id: '355', name: 'THE DAHOD MERCANTILE CO-OP BANK LTD', priority: false },
  { id: '251', name: 'The Dahod Urban Co op Bank Ltd', priority: false },
  { id: '737', name: 'The Daman and Diu State Co-op Bank Ltd', priority: false },
  { id: '438', name: 'The Darussalam Co-operative Urban Bank Ltd', priority: false },
  { id: '695', name: 'The Davangere Harihara Urban Sahakara Bank', priority: false },
  { id: '311', name: 'The Deccan Merchants Co-Operative Bank Ltd', priority: false },
  { id: '88', name: 'The Delhi Nagrik Sehkari Bank Ltd', priority: false },
  { id: '252', name: 'The Delhi State Co-operative Bank Ltd', priority: false },
  { id: '754', name: 'The Deola Merchants Co-op Bank Ltd', priority: false },
  { id: '712', name: 'The Dharmaj Peoples Co-Op Bank Ltd.', priority: false },
  { id: '253', name: 'The Eenadu Co-op Urban Bank Ltd', priority: false },
  { id: '566', name: 'The Eluri Co-Operative Urban Bank LTD', priority: false },
  { id: '106', name: 'The Financial Co-Operative Bank Ltd', priority: false },
  { id: '628', name: 'The Gadchiroli District Central Co.Op Bank Ltd', priority: false },
  { id: '511', name: 'The Gandevi People\'s Co.op Bank Ltd', priority: false },
  { id: '312', name: 'The Gandhi Gunj Co-Operative Bank Ltd', priority: false },
  { id: '406', name: 'The Gandhidham Co-Op Bank Ltd', priority: false },
  { id: '487', name: 'The Gandhidham Mercantile Co-operative Bank Ltd.', priority: false },
  { id: '605', name: 'The Gandhinagar Nagarik Co.op Bank Ltd', priority: false },
  { id: '519', name: 'The Gandhinagar Urban Co.Op Bank Ltd', priority: false },
  { id: '516', name: 'The Ganga Mercantile Urban Co-op Bank', priority: false },
  { id: '254', name: 'The Gauhati Co-op Urban Bank Ltd', priority: false },
  { id: '202', name: 'The Gayatri Co-Operative Urban Bank Ltd', priority: false },
  { id: '636', name: 'The Goa State Co-operative Bank Ltd.', priority: false },
  { id: '192', name: 'The Goa Urban Co-Operative Bank Ltd', priority: false },
  { id: '314', name: 'The Godhra City Co-op Bank Ltd', priority: false },
  { id: '193', name: 'The Godhra Urban Co-Operative Bank', priority: false },
  { id: '469', name: 'The Grain Merchants Co-operative Bank Ltd', priority: false },
  { id: '446', name: 'The Greater Bombay Co.op Bank', priority: false },
  { id: '85', name: 'The Gujarat State Co-operative Bank', priority: false },
  { id: '542', name: 'The Guntur Co-Operative Urban Bank Ltd', priority: false },
  { id: '561', name: 'The Guntur District Co-Operative Central Bank', priority: false },
  { id: '623', name: 'The Halol Mercantile Co-op. Bank Ltd', priority: false },
  { id: '738', name: 'The Halol Urban Co-op. Bank Ltd.', priority: false },
  { id: '168', name: 'The Hasti Co Op Bank Ltd', priority: false },
  { id: '131', name: 'The Hindusthan Co Operative Bank Ltd', priority: false },
  { id: '590', name: 'The Hisar Urban Co-operative Bank', priority: false },
  { id: '773', name: 'The Honavar Urban Co-Operative Bank Ltd.', priority: false },
  { id: '736', name: 'The Hooghly Co-operative Credit Bank Ltd.', priority: false },
  { id: '750', name: 'The Hotel Industrialists Co-Operative Bank Ltd.', priority: false },
  { id: '619', name: 'The Ichalkaranji Merchants Co-op Bank Ltd', priority: false },
  { id: '688', name: 'The Idar Nagarik Sahakari Bank Ltd', priority: false },
  { id: '504', name: 'The Income Tax Department Co.op Bank Ltd', priority: false },
  { id: '677', name: 'The Industrial Co operative Bank Ltd', priority: false },
  { id: '564', name: 'The Jain Sahakari Bank Ltd', priority: false },
  { id: '435', name: 'The Jaipur Central Co Operative Bank Ltd', priority: false },
  { id: '708', name: 'The Jalgaon District Central Co-Op Bank Ltd', priority: false },
  { id: '91', name: 'The Jalgaon Peoples Co-Operative Bank Ltd', priority: false },
  { id: '702', name: 'The Jalna Peoples Co-Op Bank Ltd.', priority: false },
  { id: '802', name: 'The Jalpaiguri Central Co-operative Bank Ltd', priority: false },
  { id: '527', name: 'The Jamkhandi Urban Co-Operative Bank Ltd', priority: false },
  { id: '648', name: 'The Jamnagar District Co-Operative Bank Ltd', priority: false },
  { id: '371', name: 'The Janalaxmi Co-Operative Bank Ltd', priority: false },
  { id: '116', name: 'The Janata Co-operative Bank Ltd', priority: false },
  { id: '698', name: 'The Janatha Co-operative Bank Ltd', priority: false },
  { id: '576', name: 'The Jhalod Urban Co Op Bank Ltd', priority: false },
  { id: '720', name: 'The Jharkhand State Co-op Bank Ltd', priority: false },
  { id: '505', name: 'The Jodhpur Central Co.op Bank Ltd', priority: false },
  { id: '198', name: 'The Junagadh Commercial Co-Operative Bank Ltd', priority: false },
  { id: '486', name: 'The Junagadh Jila Sahakari Bank', priority: false },
  { id: '709', name: 'The Kachchh District Central Co-Operative Bank', priority: false },
  { id: '184', name: 'The Kaira District Central Co Operative Bank Ltd', priority: false },
  { id: '549', name: 'The Kalol Nagrik Sahakari Bank Ltd.', priority: false },
  { id: '48', name: 'The Kalupur Commercial Co-Operative Bank Ltd', priority: false },
  { id: '570', name: 'The Kalwan Merchant Co-Operative Bank', priority: false },
  { id: '81', name: 'The Kalyan Janata Sahakari Bank Ltd', priority: false },
  { id: '453', name: 'The Kanaka mahalakshmi Co-Op. Bank Ltd', priority: false },
  { id: '723', name: 'The Kanara D.C.C. Bank Ltd.', priority: false },
  { id: '164', name: 'The Kangra Central Co-operative Bank Ltd', priority: false },
  { id: '256', name: 'The Kangra Co-operative Bank Ltd', priority: false },
  { id: '109', name: 'The Karad Urban Co Op Bank Ltd', priority: false },
  { id: '776', name: 'The Karnataka Central Co-operative Bank', priority: false },
  { id: '257', name: 'The Karnataka State Co-op Apex Bank Ltd', priority: false },
  { id: '150', name: 'The Karnavati Co-op Bank Ltd', priority: false },
  { id: '789', name: 'The Khambhat Nagarik Sahakari Bank Ltd.', priority: false },
  { id: '151', name: 'The Khamgaon Urban Co-op Bank Ltd', priority: false },
  { id: '833', name: 'The Khanapur Co-op Bank Ltd.', priority: false },
  { id: '401', name: 'The Khattri Co-operative Urban Bank Ltd', priority: false },
  { id: '726', name: 'The Kheda District Central Co.op Bank Ltd', priority: false },
  { id: '690', name: 'The Kheralu Nagrik sahkari Bank Ltd.', priority: false },
  { id: '457', name: 'The Kodinar Nagarik Sahakari Bank Ltd', priority: false },
  { id: '765', name: 'The Kodinar Taluka Co-operative Banking Union Ltd.', priority: false },
  { id: '679', name: 'The Kolar and Chikballapura District Co-operative Central Bank Ltd', priority: false },
  { id: '609', name: 'The Kolhapur Urban Co-op Bank Ltd', priority: false },
  { id: '460', name: 'The Kottakkal Cooperative Urban Bank Ltd', priority: false },
  { id: '412', name: 'The Koylanchal Urban Co-op Bank Ltd', priority: false },
  { id: '258', name: 'The Kukarwada Nagrik Sahakari Bank Ltd', priority: false },
  { id: '644', name: 'The Kunbi Sahakari Bank Limited', priority: false },
  { id: '478', name: 'The Kurla Nagarik Sahakari Bank Ltd', priority: false },
  { id: '259', name: 'The Kurmanchal Nagar Sahkari Bank Ltd', priority: false },
  { id: '260', name: 'The Latur Urban Co-Op Bank Ltd', priority: false },
  { id: '706', name: 'The Limdi Urban Co-op Bank Ltd', priority: false },
  { id: '554', name: 'The Lunawada Peoples Co-operative Bank Limited', priority: false },
  { id: '756', name: 'The Mahanagar Co.op Urban Bank Ltd', priority: false },
  { id: '637', name: 'The Maharashtra State Co-op.Bank Ltd', priority: false },
  { id: '525', name: 'The Mahaveer Co.op Bank Ltd', priority: false },
  { id: '361', name: 'The Malad Sahakari Bank Ltd', priority: false },
  { id: '828', name: 'The Malegaon Merchants CO-OP Bank', priority: false },
  { id: '315', name: 'The Mandvi Mercantile Co-op Bank Ltd', priority: false },
  { id: '673', name: 'The Mandvi Nagrik Sahakari Bank Ltd', priority: false },
  { id: '719', name: 'The Mangalore Catholic Co-operative Bank Ltd', priority: false },
  { id: '598', name: 'The Mangalore Co.op Town Bank Ltd', priority: false },
  { id: '502', name: 'The Manmandir Co-operative Bank Ltd', priority: false },
  { id: '417', name: 'The Mehsana District Central Co-Operative Bank Ltd', priority: false },
  { id: '76', name: 'The Mehsana Nagrik Sahakari Bank Ltd', priority: false },
  { id: '12', name: 'The Mehsana Urban Co-operative Bank Ltd', priority: false },
  { id: '316', name: 'The Merchants Urban Co-op Bank Ltd', priority: false },
  { id: '496', name: 'The Modasa Nagarik Sahakari Bank Ltd', priority: false },
  { id: '344', name: 'The Mogaveera Co-Operative Bank Ltd', priority: false },
  { id: '718', name: 'The Moti Urban Co-op Bank Ltd', priority: false },
  { id: '364', name: 'The Municipal Co-op Bank Ltd', priority: false },
  { id: '261', name: 'The Muslim Co-Operative Bank Ltd', priority: false },
  { id: '716', name: 'The Mysore and Chamarajanagar District Central Co-op Bank Ltd', priority: false },
  { id: '262', name: 'The Mysore Merchants Co-op Bank Ltd', priority: false },
  { id: '740', name: 'The Nagaland State Co-op Bank Ltd', priority: false },
  { id: '419', name: 'The Nanded Merchant\'s Co-op bank Ltd', priority: false },
  { id: '670', name: 'The Nandura Urban Co Op Bank Ltd.', priority: false },
  { id: '540', name: 'The Nandurbar Merchants Co-operative Bank', priority: false },
  { id: '437', name: 'The Naroda Nagrik Co-op Bank Limited', priority: false },
  { id: '557', name: 'The Nashik Road Deolali Vyapari Sahakari Bank Ltd', priority: false },
  { id: '317', name: 'The National Co-operative Bank', priority: false },
  { id: '166', name: 'The Navnirman Co-Operative Bank Limited', priority: false },
  { id: '456', name: 'The Nawanagar Co.op Bank Ltd', priority: false },
  { id: '264', name: 'The New Urban Co-op Bank Ltd', priority: false },
  { id: '373', name: 'The Ojhar Merchants Co-op Bank Ltd', priority: false },
  { id: '794', name: 'The Pachora Peoples Co-Operative Bank Ltd.', priority: false },
  { id: '579', name: 'The Panchmahal District Co-Operative Bank Ltd.', priority: false },
  { id: '53', name: 'The Panchsheel Mercantil Co Op Bank Ltd', priority: false },
  { id: '743', name: 'The Pandharpur Merchant\'s Co-op Bank Ltd', priority: false },
  { id: '265', name: 'The Pandharpur Urban Co-Op Bank Ltd', priority: false },
  { id: '195', name: 'The Panipat Urban Co-operative Bank Ltd', priority: false },
  { id: '602', name: 'The Panvel Co-op Urban Bank Ltd', priority: false },
  { id: '660', name: 'The Parbhani District Central Co.op Bank Ltd', priority: false },
  { id: '235', name: 'The Pimpalgaon Merchants Co-op Bank Ltd', priority: false },
  { id: '715', name: 'The Pioneer Urban Co-Operative Bank Ltd.', priority: false },
  { id: '387', name: 'The Pragati Urban Co-op Bank Ltd', priority: false },
  { id: '618', name: 'The Pratap Co-Op. Bank Ltd.', priority: false },
  { id: '514', name: 'The Raddi Sahakara Bank', priority: false },
  { id: '368', name: 'The Raipur Urban Mercantile Co-Op Bank Ltd', priority: false },
  { id: '339', name: 'The Raj Laxmi Mahila Urban Co Op Bank Limited', priority: false },
  { id: '459', name: 'THE RAJASTHAN STATE CO-OP BANK', priority: false },
  { id: '335', name: 'The Rajasthan Urban Co-Operative Bank Ltd', priority: false },
  { id: '354', name: 'The Rajkot Commercial Co op Bank Ltd', priority: false },
  { id: '585', name: 'The Rajsamand Urban Co-operative Bank', priority: false },
  { id: '110', name: 'The Rander Peoples Co Op Bank Ltd', priority: false },
  { id: '568', name: 'The Ranuj Nagrik Sahkari Bank Ltd', priority: false },
  { id: '805', name: 'The Revdanda Co-op Urban Bank', priority: false },
  { id: '266', name: 'The Sabarkantha District Central Co op Bank Ltd', priority: false },
  { id: '652', name: 'The Sahasrarjun Seva Kalyan Co-Op Bank Ltd', priority: false },
  { id: '744', name: 'The Sahyadri Sahakari Bank Ltd.', priority: false },
  { id: '829', name: 'The Salem District Central Co-operative Bank Ltd.', priority: false },
  { id: '158', name: 'The Samata Urban Co Operative Credit Society Ltd', priority: false },
  { id: '318', name: 'The Sangamner Merchants Co Operative Bank Ltd', priority: false },
  { id: '551', name: 'The Sankheda Nagarik Sahkari Bank Limited', priority: false },
  { id: '319', name: 'The Santrampur Urban Co-op Bank Ltd', priority: false },
  { id: '330', name: 'The Sarangpur Co-op Bank Ltd', priority: false },
  { id: '523', name: 'The Sardargunj Mercantile Co.Op.Bank Ltd', priority: false },
  { id: '15', name: 'The Sarvodaya Sahakari Bank Ltd', priority: false },
  { id: '200', name: 'The Satara District Central Co-Op Bank', priority: false },
  { id: '347', name: 'The Satara Sahakari Bank Ltd', priority: false },
  { id: '71', name: 'The Saurashtra Co-op Bank Ltd', priority: false },
  { id: '180', name: 'The Sevalia Urban Co-operative Bank', priority: false },
  { id: '586', name: 'The Shahada People\'s Co-op Bank Ltd', priority: false },
  { id: '320', name: 'The Shimoga Arecanut Mandy Merchants Co- Op Bank Ltd', priority: false },
  { id: '267', name: 'The Shirpur Peoples Co-Operative Bank Ltd', priority: false },
  { id: '532', name: 'The Sirsi Urban Sahakari Bank Ltd', priority: false },
  { id: '603', name: 'The Solapur District Central Co-Op Bank Ltd', priority: false },
  { id: '468', name: 'The Solapur Social Urban Co-Op Bank Ltd', priority: false },
  { id: '801', name: 'The Sonepat Central Cooperative Bank Ltd.', priority: false },
  { id: '167', name: 'The Sonepat Urban Co-operative Bank', priority: false },
  { id: '472', name: 'The South Canara District Central Co.op Bank', priority: false },
  { id: '694', name: 'The SPSR Nellore District Co-op Central Bank Ltd', priority: false },
  { id: '832', name: 'The Sultan\'s Battery Co-operative Urban Bank Ltd.', priority: false },
  { id: '39', name: 'The Surat District Co-op Bank Ltd', priority: false },
  { id: '52', name: 'The Surat Mercantile Co-op Bank Ltd', priority: false },
  { id: '17', name: 'The Surat People\'s Co-operative Bank Ltd', priority: false },
  { id: '30', name: 'The Sutex Co-operative bank Ltd', priority: false },
  { id: '268', name: 'The Swasakthi Mercantile Co op Urban Bank Ltd', priority: false },
  { id: '830', name: 'The Tamil Nadu State Apex Co-operative Bank Ltd.', priority: false },
  { id: '403', name: 'The Tasgaon Urban Co-op Bank Ltd', priority: false },
  { id: '190', name: 'The Thane District Central Co-Op Bank Ltd', priority: false },
  { id: '731', name: 'The Tirur Urban Co-operative Bank Ltd', priority: false },
  { id: '749', name: 'The Town co-operative bank Ltd.', priority: false },
  { id: '385', name: 'The Udaipur Mahila Samridhi Urban Co-op Bank Ltd', priority: false },
  { id: '645', name: 'The Udaipur Mahila Urban Co-Op. Bank Ltd', priority: false },
  { id: '269', name: 'The Udaipur Urban Co-op Bank Ltd', priority: false },
  { id: '748', name: 'The Udupi Cooperative Town Bank Ltd.', priority: false },
  { id: '807', name: 'The Umreth Urban Co-operative Bank Ltd', priority: false },
  { id: '820', name: 'The Una Peoples Co-op Bank Ltd', priority: false },
  { id: '203', name: 'The Union Co-operative Bank Ltd', priority: false },
  { id: '503', name: 'The United Co-Operative Bank Ltd.', priority: false },
  { id: '295', name: 'The Urban Co-op Bank Ltd', priority: false },
  { id: '642', name: 'The Vaidyanath Urban Co-Op Bank Ltd', priority: false },
  { id: '461', name: 'The Vaijapur Merchants Co Operative Bank', priority: false },
  { id: '777', name: 'The Vaish Co-Op. New Bank Ltd.', priority: false },
  { id: '404', name: 'The Vallabh Vidyanagar Commercial Co op Bank Ltd', priority: false },
  { id: '553', name: 'The Valsad District Central Co. Op. Bank Ltd.', priority: false },
  { id: '20', name: 'The Varachha Co-op Bank Ltd', priority: false },
  { id: '87', name: 'The Vasai Vikas Sahakari Bank Ltd', priority: false },
  { id: '745', name: 'The Vepar Udhyog Vikas Sahkari Bank Ltd.', priority: false },
  { id: '482', name: 'The Veraval Mercantile Co Op Bank Ltd', priority: false },
  { id: '696', name: 'The Veraval People\'s Co-Op. Bank Ltd', priority: false },
  { id: '270', name: 'The Vijay Co-operative Bank Ltd', priority: false },
  { id: '629', name: 'The Vijaypur District Central Co-op Bank Ltd', priority: false },
  { id: '471', name: 'The Visakhapatnam Co-operative Bank Ltd', priority: false },
  { id: '154', name: 'The Vishweshwar Sahakari Bank', priority: false },
  { id: '614', name: 'The Vyankateshwara Sahakari Bank Ltd', priority: false },
  { id: '321', name: 'The Waghodia Urban Co-op Bank Ltd', priority: false },
  { id: '271', name: 'The Wai Urban Co-operative Bank Ltd', priority: false },
  { id: '367', name: 'The Wardhman Urban Co-operative Bank Ltd', priority: false },
  { id: '396', name: 'The Washim Urban Co-Operative Bank Ltd', priority: false },
  { id: '751', name: 'The West Bengal State Co-operative Bank Ltd.', priority: false },
  { id: '333', name: 'The Yavatmal Urban Co-Op Bank Ltd', priority: false },
  { id: '107', name: 'The Zoroastrian Co-operative Bank', priority: false },
  { id: '450', name: 'Tirupati Urban Co-Operative Bank Ltd', priority: false },
  { id: '47', name: 'TJSB Sahakari Bank Ltd', priority: false },
  { id: '153', name: 'TTC Co-Operative Bank Limited', priority: false },
  { id: '509', name: 'Tumkur Grain Merchants Co-op Bank (TGMC)', priority: false },
  { id: '408', name: 'Udyam Vikas Sahakari Bank Ltd', priority: false },
  { id: '18', name: 'Ujjivan Small Finance Bank Ltd', priority: false },
  { id: '272', name: 'Uma Co-op Bank Ltd', priority: false },
  { id: '136', name: 'Umiya Urban Co Operative Bank', priority: false },
  { id: '340', name: 'Unity Small Finance Bank Ltd', priority: false },
  { id: '322', name: 'Unjha Nagrik Sahakari Bank', priority: false },
  { id: '161', name: 'Utkal Grameen Bank', priority: false },
  { id: '63', name: 'Utkarsh Small Finance Bank', priority: false },
  { id: '182', name: 'Uttar Bihar Gramin Bank', priority: false },
  { id: '513', name: 'Uttar Pradesh Co-op Bank Ltd', priority: false },
  { id: '672', name: 'Uttar Pradesh Gramin Bank', priority: false },
  { id: '323', name: 'Uttarakhand Gramin Bank', priority: false },
  { id: '273', name: 'Uttarbanga Kshetriya Gramin Bank', priority: false },
  { id: '671', name: 'Uttrakhand Co-operative Bank Ltd', priority: false },
  { id: '443', name: 'Vadnagar Nagarik Sahakari Bank Ltd', priority: false },
  { id: '99', name: 'Vaishya Nagari Sahakari Bank Ltd', priority: false },
  { id: '491', name: 'Vaishya Sahakari Bank Ltd', priority: false },
  { id: '550', name: 'Valmiki Urban Co-Op Bank Ltd', priority: false },
  { id: '827', name: 'Vani Merchants Co-operative Bank', priority: false },
  { id: '545', name: 'Vardhaman Mahila Co-op. Urban Bank Ltd', priority: false },
  { id: '274', name: 'Vasai Janata Sahakari Bank Ltd', priority: false },
  { id: '275', name: 'Vasavi MSCM Co-operative Bank Ltd', priority: false },
  { id: '791', name: 'Veerashaiva Sahakari Bank', priority: false },
  { id: '118', name: 'Vidarbha Merchants Urban Co-op Bank Ltd', priority: false },
  { id: '377', name: 'Vidya Sahakari Bank Ltd', priority: false },
  { id: '324', name: 'Vidyanand Co-op Bank Ltd', priority: false },
  { id: '451', name: 'Vijay Commercial Co.op Bank Ltd.', priority: false },
  { id: '276', name: 'Vijaya Bank', priority: false },
  { id: '685', name: 'Vikas Sahakari Bank Ltd', priority: false },
  { id: '186', name: 'Vikas Souharda Co Op Bank Ltd', priority: false },
  { id: '601', name: 'Vikramaditya Nagrik Sahkari Bank', priority: false },
  { id: '836', name: 'Vishwakarma Sahakara Bank', priority: false },
  { id: '559', name: 'Vishwas Co-operative Bank Ltd', priority: false },
  { id: '581', name: 'Vyapari Sahakari Bank Maryadit', priority: false },
  { id: '717', name: 'Vyaparik Audhyogik Sahakari Bank LTD.', priority: false },
  { id: '500', name: 'Vyavsayik Sahakari Bank Ltd', priority: false },
  { id: '759', name: 'Vysya Co-operative Bank Ltd', priority: false },
  { id: '382', name: 'Wana Nagarik Sahakari Bank Ltd', priority: false },
  { id: '727', name: 'Warangal Urban Cooperative Bank Ltd', priority: false },
  { id: '436', name: 'Wardha Nagari Sahakari Adhikosh Bank', priority: false },
  { id: '734', name: 'West Bengal Gramin Bank', priority: false },
  { id: '817', name: 'Yavatmal District Central Co-operative Bank', priority: false },
  { id: '713', name: 'Yeshwant Nagari Sahakari Bank Ltd.', priority: false },
  { id: '197', name: 'Zenith Bank', priority: false },
  { id: '0', name: 'Other Bank', priority: false },
];
